modLoader="javafml"
loaderVersion="[36,)"
license="license.txt"
issueTrackerURL="https://github.com/InfinityRaider/MineyGames/issues/"

[[mods]]
modId="miney_games"
version="1.18.2-1.0.0"
displayName="Miney Games"
displayURL="https://www.curseforge.com/minecraft/mc-mods/miney-games"
updateJSONURL = "https://raw.githubusercontent.com/InfinityRaider/MineyGames/master/version.json"
logoFile="logo.png"
authors="InfinityRaider"
description='''
Mini-games in Minecraft
'''

[[dependencies.miney_games]]
    modId="forge"
    mandatory=true
    versionRange="[40.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.miney_games]]
    modId="infinitylib"
    mandatory=true
    versionRange="[1.18.2-2.1.3,)"
    ordering="AFTER"
    side="BOTH"